[CONFIG]
config_file= "/etc/aisuan/config.toml" #配置文件
main_file = "/usr/local/bin/aisuan"  #主程序
DEBUG = true  #调试模式
fd_path = "/home/aisuan/fd"  #fieldiag路径
gpu_burn_path = "/home/aisuan/gpu_burn"  #gpu_burn路径
nccl_path = "/home/aisuan/nccl"  #nccl测试路径

[UPDATE]
update_file = "/usr/local/bin/aisuan"  #更新文件
update_url = "http://192.168.1.1:8080/update.json"  #更新地址

[LOG]
log_path = "/home/aisuan/log"  #日志路径
log_file = "aisuan.log"  #日志文件
log_level = "DEBUG"  #日志级别
console_output = false
