[CONFIG]
version = "1.0.5"  #版本号
config_file= "/etc/aisuan/config.toml" #配置文件
main_file = "/usr/local/bin/aisuan"  #主程序
DEBUG = false  #调试模式
fd_path = "/home/aisuan/fd"  #fieldiag路径
gpu_burn_path = "/home/aisuan/gpu-burn"  #gpu_burn路径
nccl_path = "/home/aisuan/nccl"  #nccl测试路径
fd_exe = "fieldiag.sh"  #fieldiag可执行文件
gpu_burn_exe = "gpu_burn"  #gpu_burn可执行文件
nccl_exe = "all_reduce_perf"  #nccl可执行文件


[UPDATE]
#待实现，不用管
url = "http://192.168.10.20"  #更新地址
update_file = "/aisuan"  #更新文件路径
update_config = "/update.json"  #更新配置文件

[LOG]
log_path = "/home/aisuan/log"  #日志路径
log_file = "aisuan.log"  #日志文件
log_level = "DEBUG"  #日志级别
console_output = false


[MENU]
