name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ clang lld make patchelf python3-dev ccache python3
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install noneprompt toml Nuitka
        
    - name: Build with Nuitka
      run: make nuitka
      
    - name: Compress with UPX
      run: |
        sudo apt-get install -y upx
        make upx
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/
        
    - name: Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
